remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Home - Cristiana SP de Alencar]
description: [A hopefully-not-boring blog about my projects.]
